//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietKhoGame
    {
        public int MaKhoGame { get; set; }
        public int MaGame { get; set; }
        public Nullable<System.DateTime> NgayThem { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual KhoGame KhoGame { get; set; }
    }
}
