//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoAn3Entities : DbContext
    {
        public DoAn3Entities()
            : base("name=DoAn3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BinhLuan> BinhLuan { get; set; }
        public virtual DbSet<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual DbSet<ChiTietKhoGame> ChiTietKhoGame { get; set; }
        public virtual DbSet<DonHang> DonHang { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<KhoGame> KhoGame { get; set; }
        public virtual DbSet<Like> Like { get; set; }
        public virtual DbSet<LoaiGame> LoaiGame { get; set; }
        public virtual DbSet<LoaiMay> LoaiMay { get; set; }
        public virtual DbSet<News> New { get; set; }
        public virtual DbSet<NhaPhatHanh> NhaPhatHanh { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
