//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Banner { get; set; }
        public System.DateTime PublicDate { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual LoaiGame LoaiGame { get; set; }
        public virtual User User { get; set; }
    }
}
